version: '3.7'
volumes:
  pgdata:
    name: pgdata
services:
  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data
    build:
      context: ./
      dockerfile: postgres-multiple-db.Dockerfile
    environment:
      POSTGRES_USER: talismane
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 
      POSTGRES_MULTIPLE_DATABASES: '"terms","terms-test"'
    ports:
      - "${TALISMANE_DATABASE_PORT:-5432}:5432"
